src/views/types/ParmTreeItem.ts

Switch icons for IN and OUT parameters in Schema Browser
Issue #16

Switch icons for IN and OUT parameters in Schema Browser

---

src/language/sql/document.ts
src/language/sql/statement.ts
src/language/sql/tests/blocks.test.ts
src/language/sql/tokens.ts
src/language/sql/types.ts

Adds new API to get document definitions

Provide API and tests to document definitions

---

package.json
src/config.ts
src/configuration.ts
src/connection/manager.ts
src/connection/serverComponent.ts
src/views/jobManager/jobManagerView.ts

* New UI to ask the user if they want to automatically start up a job
* New logic to check for installation
* Cleanup of unused configuration options

Ability to automatically start SQL Job

---

src/views/results/index.ts

SQL runner now supports:
* create+begin statements (procedures/functions mostly)
* compound statements!

Use tokeniser to select value statement group

---

src/connection/serverComponent.ts
src/connection/types.ts
src/testing/jobs.ts

Fix errors when certain SQL statements return no result set

---

package.json
src/extension.ts
src/views/schemaBrowser/copyUI.ts
src/views/schemaBrowser/schemaBrowser.ts

Fixes halcyon-tech/vscode-db2i#34

Add form validation, move copyUI to own file

---

src/connection/serverComponent.ts
src/connection/types.ts
src/views/results/html.ts
src/views/results/index.ts

Add update count to user message when no results are returned

---

src/connection/manager.ts
src/connection/query.ts
src/connection/serverComponent.ts
src/connection/types.ts
src/testing/jobs.ts
src/views/results/html.ts
src/views/results/index.ts

Handle terse data format from server for SQL results

---

src/connection/serverComponent.ts

After updating the [CodeForIBMiServer](https://github.com/ThePrez/CodeForIBMiServer) jar in the user's home directory on the i, delete the temp file from their workstation.

Cleanup temp file

---

src/language/providers/completionProvider.ts

Adds environment variable to make it possible to disable the content assist

Ability to disable content assist

---

.gitignore
.vscodeignore
package-lock.json
package.json
src/connection/manager.ts
src/extension.ts
src/views/jobManager/jobManagerView.ts

- Exported `SQLJobManager` and `SQLJob`
- Add `getAllJobs` function to the `SQLJobManager`
- Added script to generate types, but excluded them from this repo (we will manually copy over the types to our extension)

Export the `SQLJobManager` API to be used in Merlin

---

src/language/sql/document.ts
src/language/sql/statement.ts
src/language/sql/tests/statements.test.ts
src/language/sql/tokens.ts

* Statement API to get embedded areas
* Document API to cleanup embedded statements
* Tests for different embedded scenarios

APIs for embedded SQL

---

package-lock.json

Packages and versions were not updated in the package-lock.json file...

Update package-lock to correct packages and version numbers

---

src/connection/SCVersion.ts
src/database/schemas.ts

* Fixes and closes #173
* Updated Server Component to 1.7.3

Stop automatically formatting with Generate SQL feature

---

src/connection/SCVersion.ts
src/testing/jobs.ts

fix: server trace entries overflowing

---

src/views/results/index.ts

* Show better state based when using a prefix
* Generate smaller SQL insert statements when using `sql:` prefix.

Improved UX for using statement prefixes

---

src/connection/serverComponent.ts

Fixes #76
> Server component is installed with public read authority, perhaps should/could be public *EXCLUDE

Add calls to change permissions of server component

---

README.md

* Added link to docs in readme (#218)
* Clean-up/formatting (halcyon to codefori, fixed numbering issue)

Added link to docs for Issue #218

---

package.json
src/views/schemaBrowser/schemaBrowser.ts
src/views/schemaBrowser/statements.ts

* "Get Indexes" on tables now more detailed and includes MTI info where applicable
* Right click on either tables or schemas a new "Get MTIs" option will be available.

Get MTIs for a schema or table, improved index info

---

src/database/schemas.ts

Implements #262.
Extends the Tables node to include MQTs.

Also show MQTs in Tables node

---

src/notebooks/Controller.ts

check if data is returned from query in notebooks

---

src/database/schemas.ts
src/views/schemaBrowser/index.ts

Adds the 'Logicals' node to the Schema Browser.

Logicals available from the Schema Browser

---

.gitignore
.vscodeignore
package.json
src/aiProviders/context.ts
src/aiProviders/continue/listTablesContextProvider.ts
src/database/callable.ts
src/database/schemas.ts
src/database/table.ts
src/database/view.ts
src/language/providers/completionProvider.ts
src/language/providers/logic/cache.ts
src/language/providers/logic/callable.ts
src/language/providers/logic/completion.ts
src/types.ts
src/views/jobManager/editJob/formatTab.ts
src/views/jobManager/editJob/index.ts
src/views/jobManager/editJob/otherTab.ts
src/views/jobManager/editJob/perfTab.ts
src/views/jobManager/editJob/sortTab.ts
src/views/jobManager/editJob/systemTab.ts
src/views/results/resultSetPanelProvider.ts
src/views/schemaBrowser/index.ts
src/views/types/ColumnTreeItem.ts
src/views/types/ParmTreeItem.ts

Refactor type definitions and improve error collection mechanisms. Introduce a new command for type checking and enhance typings throughout the codebase.

Enhance type safety and error handling

---

package-lock.json
package.json
src/connection/SCVersion.ts
src/connection/manager.ts
src/connection/sqlJob.ts
src/connection/types.ts
src/database/schemas.ts
src/language/providers/completionProvider.ts
src/views/jobManager/jobManagerView.ts
src/views/results/index.ts

Update the Mapepire version to 2.2.1 in the codebase.
Run: `npm run dsc` before debugging.
* Updates Mapepire-server
* Updates Mapepire-client
* Cleanup how objects are fetched significantly

Bump Mapepire version to 2.2.2

---

package-lock.json
package.json
src/views/results/codegen.test.ts
src/views/results/codegen.ts
src/views/results/contributes.json
src/views/results/index.ts

RPG symbol name using name or label. Remove non-alphanum chars

---

src/connection/SCVersion.ts

Update the server version to 2.3.3 in the codebase.
* Fixes #395
* Fixes #388

Bump mapepire server version to 2.3.3
