codefori/vscode-db2i

- src/connection/types.ts
- src/views/jobManager/editJob/index.ts
- src/views/jobManager/editJob/otherTab.ts
- src/views/jobManager/editJob/perfTab.ts
- src/views/jobManager/editJob/systemTab.ts
Uses `boolean` type over string type `"true"|"false"` for JDBC options. Also updated UI to respect true/false values as boolean types.
> Use boolean over "true" and "false" strings

- src/connection/serverComponent.ts
- src/testing/jobs.ts
- src/testing/manager.ts
I noticed the tests were running slow and it's because we're checking if the server component is installed on every single test.
We only need to check if it's installed in the first test case, then we check the local property after that.
> Remove server component check after first

- package.json
Changes "Copy Job ID" to "Copy Job Name" to follow the standard of using "name".
> Change "Job ID" to "Job Name" in UI

- src/views/results/html.ts
- src/views/results/index.ts
Running the same statement multiple times resulted in an error saying "Statement has already been run" or "Statement has already been fully run."
Root cause is that we're reusing the web view to post result sets. We may want to revisit that core design decision in the future, but for now, we can simply reset the query object used in the view.
> bugfix: "Statement has already been fully run"

- src/connection/sqlJob.ts
- src/views/jobManager/jobManagerView.ts
- src/views/jobManager/statusBar.ts
- src/views/results/index.ts
A new status bar item has been added that will:
* Have quick access to the job log and connection settings view
* Changes colour if there are pending uncommitted changes when using commitment control
* Shows how many many changes along with commit and rollback buttons.
* Stops jobs from ended when there are pending changes remaining without deciding what to do with them.
To test:
* Change isolation level from none
* Set auto commit to false
> Status Bar item with commitment controls

- src/language/sql/statement.ts
- src/language/sql/tests/statements.test.ts
- src/language/sql/tokens.ts
- src/language/sql/types.ts
Fixes #77 by adding support the `ALTER` statement type and object reference support.
> Add ALTER support to tokeniser (#77)

- .github/workflows/webpack_ci.yaml
Fix an issue that sometimes caused files in the CI-built test package to be created with an incorrect file extension
> Fixup building of `.vsix` in CI

- package.json
- src/database/schemas.ts
- src/views/schemaBrowser.ts
Ready for review and some testing.  Fixes #61 
The input prompt for adding a schema to the Schema Browser will now:
1. Validate the input to prevent duplicate entries.  Validation is performed on every keystroke, so checking for duplicates can be done in the validator, but verifying existence needs to wait until the user presses Enter.
2. Verify existence of the schema entered, displaying an error when it does not.  Unfortunately the `InputBox` construct does not seem to allow for validation upon the user pressing Enter, so for now it simply displays an error.  We could swizzle it to re-display the `InputBox` with the value prefilled and additional validation code that would highlight the value as an error.
Also added a schema browser for quickly adding one or more schemas.
Display …
> Validate user-entered schema / Browse to add schemas

- src/connection/manager.ts
Simple fix to the `Close Job` action so that it closes the right job instead of always closing the first one.
> Fix incorrect SQL job being closed

- src/language/sql/document.ts
- src/language/sql/statement.ts
- src/language/sql/tests/statements.test.ts
- src/language/sql/types.ts
- src/views/results/index.ts
When a statement is ran, but has host parameters, user will be expected to fix them up before the statement can be executed.
The statement will not execute and the user will be able to tab through the parameters to set the values.
> Host parameters treated like snippets

- src/language/sql/statement.ts
- src/language/sql/tests/statements.test.ts
Fixes bug where `INTO` clause was being removed during `INSERT` statement.
> Better support for finding statement type when EXEC is used

- package-lock.json
- package.json
- src/configuration.ts
- src/database/statement.ts
This PR will
- update the [SQL formatter](https://github.com/sql-formatter-org/sql-formatter) to the current version of 13.1.0
- use the new language `db2i` implemented in SQL Formatter version 13.1.0
- add a configuration value `sqlFormat.keywordCase` to allow the user to have SQL keywords in lower- or uppercase
With this PR and a configuration setting of `lower`, the generated SQL for `QGPL.QAIDRKEYS` will be like this:
Before this would be formatted like this:
> Update SQL formatter and allow SQL keyword in lower- or uppercase

- src/database/statement.ts
- src/language/index.ts
- src/language/providers/formatProvider.ts
Since we have a nicer SQL formatter now, I have decided to add a format provider which enables the standard 'Format Document' to work with SQL sources.
> Add new format provider

- package-lock.json
- package.json
- src/database/statement.ts
This PR will
- update SQL formatter to version 14.0.0, which includes the new option for identifier formatting
- add a configuration value `sqlFormat.identifierCase` to allow the user to have SQL identifier in lower- or uppercase or not changed. Default is `preserve` to not change the identifier case unintentionally.
With this support the following SQL statement
will be formatted like this (with identifiers set to uppercase and keywords to lowercase):
> Add SQL identifier case - new in SQL formatter 14.0.0

- src/config.ts
- src/views/results/index.ts
Fixes #174.
Will reset the results view when disconnecting from a system so it is back to normal when connecting to a new system.
> Reset the results view on disconnect

- src/language/sql/statement.ts
Fixes issue where a DECLARE block (`DECLARE .. BEGIN`) was not being considered when parsing statements.
> Fix issue with DECLARE blocks not being considered

- src/config.ts
This PR changes the use of `||` in SQL statement to `concat` - the `|` is a variant character...
> Don't use variant characters in SQL statement

- package-lock.json
- package.json
- src/database/serviceInfo.ts
- src/views/examples/exampleBrowser.ts
- src/views/examples/index.ts
I noticed that the Examples browser looped when loading if no SQL job was started, because loading the Services called `refresh` which in turn called `getChildren`...and if the Services are still undefined (because no SQL job), then it loops.
So this PR fixes that. Loading the Services example doesn't call `refresh` anymore (it wasn't needed in the first place), and an information item is displayed under the Service folder to ask for an SQL job.
A `Reload` was added to the browser to allow to reload the Services example if needed.
The Examples are now sorted alphabetically and their icon is the SQL file's.
> Examples browser cleanup

- package.json
Both IBM i Project Explorer and the DB2 for i extensions have the same contextual titles for their views, which is confusing if both are moved at the bottom:
This PR renames this extension's to `DB2 for i`:
> Change Result view ocntextual title to "DB2 for i"

- src/views/results/explain/advice.ts
- src/views/results/index.ts
Simply moves the logic that generates the advice script content to another file to slim down the result set file size.
> Move advice generation to other file

- src/database/schemas.ts
Fixes https://github.com/codefori/vscode-db2i/issues/197
The query run when fetching the objects for the schemas browser was supposed to order the items alphabetically but the `Select * (...) Union All` applied to join the queries would prevent it.
This PR fixes this and restores the alphabetical order in the schemas browser.
> Fixed schema objects ordering

- src/database/schemas.ts
- src/testing/database.ts
* Wrap `select` statements for multiple object types in a `with` clause to enable schema filtering to work again
> Use `with` statement for filtering to work

- src/views/html.ts
When the theme was Light+, the ship was blended into the background.
> Change colour of ship base

- src/language/sql/document.ts
Even though this statement was invalid, it was not runnable because it was not being registered as valid group.
```
create or replace procedure coolstuff.selfrocks()
begin
select count(*) into novar from mylib.nofile
end;
```
> Fix for when group exists without end block

- src/views/results/resultSetPanelProvider.ts
The Cancel button in the editor title was not turned off when a query ended in error.
This PR turns the Cancel button off regardless of the query's end status.
- Run a query that crashes: `select * from nothing`
- The cancel button must be turned off
- Run a query that is successful: 'select * from qsys2.netstat_info'
- The cancel button must be turned off as well
> Always turn cancel button off when a query is done

- src/connection/sqlJob.ts
Previously, when editing job settings, the new job would be successfully created. But, it was still in `ended` state. This solves that problem so job settings can be changed correctly.
> Fix issue where reconnected job had a bad status

- src/views/results/resultSetPanelProvider.ts
This PR fixes an issue causing the ResultSet view to not grab the focus when running a statement after disconnecting and reconnecting to an IBM i.
This was caused by the `ResultSetPanelProvider` not keeping track of the `disposed` status of the webview, preventing the `ensureActivation` from working properly.
By resetting the reference to the resolved webview once it's disposed, the `ensureActivation` method can work as expected after reconnecting to a system.
1. Connect to an IBM i
2. Run a statement
3. The Result Set webview must grab the focus and display the results
4. Disconnect
5. Connect again
6. Run a statement
7. The Result Set webview must grab the focus and display the results again
Without this PR, step `7.` doesn't happen and the user must manually reveal the result set …
> Fix resultSet view not grabing focus after reconnection

- src/views/results/index.ts
Fixes a bug where CLs wouldn't run when the statement contained new line characters.
> Fix CL statements over multiple lines

- src/config.ts
- src/extension.ts
- src/views/examples/exampleBrowser.ts
- src/views/jobManager/jobManagerView.ts
- src/views/jobManager/selfCodes/nodes.ts
- src/views/jobManager/selfCodes/selfCodesResultsView.ts
Adds the following functionality:
* SELF errors can now be expanded to show more information we didn't show before, including client name, program and object
* We also include the stack trace for the self error in a nicely formatted view
* Fixes bug where first job after connecting to the server was not setting the SELF code
> Add SelfIleStackFrame and InitialStackData interfaces for SELF

- package.json
- src/Storage.ts
- src/config.ts
- src/views/queryHistoryView.ts
* Change how we store history internally (no longer a list of strings)
* Group statements by simple period (past day, past week, past month, later)
* All but first are collapsed by default
warning: if you test this PR, it will break your existing query history
> List query history by date

- src/views/html.ts
- src/views/results/html.ts
The results table view features a span that is updated with status, eg. statement running, row count...
The problem is that with a larger result set, the span remains out of view at the bottom until all rows have been retrieved and the result table scrolled to the end.
This PR fixes the issue by adding a footer to the table where the status is always displayed.
> Add footer to results table so status is always visible

- package.json
- src/IBMiDetail.ts
- src/config.ts
- src/connection/manager.ts
- src/extension.ts
- src/views/examples/exampleBrowser.ts
- src/views/jobManager/jobManagerView.ts
- src/views/jobManager/selfCodes/selfCodesResultsView.ts
* Cleans up the logic that determines the OS version, Db2 level and what features are enabled by moving all the logic into an IBM i class, which we can use to tie this kind of information to.
* Fixes a bug where when connecting to a system, but the user doesn't have correct authority to `group_ptf_info`, then it would 
* a) not finish the startup process correctly, 
* b) completely disabled SELF, and 
* c) failed to start a job up automatically based on the configured option
* Fixes invalid hoover tooltip on SELF stack
> Cleanup of code that checks OS version and features

- src/connection/query.ts
- src/views/results/html.ts
- src/views/results/resultSetPanelProvider.ts
Simply adds the executing job id to the footer of the result set.
> Add job id to result set footer

- src/views/results/html.ts
Fix a bug introduced by PR #224
A non-existent variable is referenced in the javascript in the generated HTML for displaying results.
Change to use the correct variable.
Fixes issue #228
> Fix reference to non-existent variable

- src/language/providers/completionProvider.ts
When using the dot trigger in a `CALL` statement, to get a list of callable procedures in a schema, the list was showing all non-procedure objects.
This will fix it so only procedures are shown.
> Fix issue with calling qualified procedure

- package.json
- src/connection/manager.ts
- src/views/html.ts
- src/views/results/html.ts
- src/views/results/index.ts
- src/views/results/resultSetPanelProvider.ts
Adds a new button the execute dropdown to run the statement in a new view.
This will run the statement in a brand new tab instead of the standard webview.
> Enable result sets in webviews

- package.json
- src/extension.ts
- src/views/jobManager/selfCodes/selfCodesResultsView.ts
This PR adds the ability to toggle SELF to only show SELF logs for the selected job. 
When it is toggled on, we can also show the job log for the selected job.
> Ability to toggle self for specific job

- package.json
- snippets/create.code-snippets
- src/language/providers/completionProvider.ts
- src/language/providers/parameterProvider.ts
- src/language/sql/statement.ts
- src/language/sql/tests/statements.test.ts
- src/language/sql/tokens.ts
* Adds support to content assist to show location definitions in source without reaching out to the server
* local `declare` variables and cursors
* procedure and function parameters
* Improvements to supporting `declare` and `create variable`
* Fix to parameter provider crashing when not connected to a system
* Show variables in schemas for regular content assist
* Open any SQL file where you have a few create statements, and prompt for the content assist, or
* Clone [this repo](https://github.com/ThePrez/WatsonX-SDK-Db2-IBMi) and try it out on some of the local sources
> Add local content assist, improve remote assist

- src/views/jobManager/selfCodes/selfCodesResultsView.ts
This fixes a seriously SELF performance issue by only showing logs for the user since the selected job has started.
> Only show SELF logs that since the selected job has started

- package-lock.json
- package.json
- src/config.ts
- src/extension.ts
- src/testing/index.ts
- src/views/schemaBrowser/index.ts
* Replace deprecated `onEvent` listener in place of `subscribe`
* Fix bug where tests were starting before server component was installed.
> Update vscode-ibmi event listener and test runner

- package.json
- src/contributes.json
- src/extension.ts
- src/uriHandler.ts
Open a statement via URI and runable by another parameter. Can only load `select` and `with` statements.
1. checkout the branch
2. build and launch the branch through debug
3. going to a URI:
* vscode://halcyontechltd.vscode-db2i/sql?content=select%20*%20from%20sample.employee&run=true
* vscode://halcyontechltd.vscode-db2i/sql?content=select%20*%20from%20sample.employee
(GitHub won't turn these into hyperlinks. Slack does)
> Ability to run a statement via URI

- src/language/sql/document.ts
- src/language/sql/statement.ts
- src/language/sql/tests/blocks.test.ts
- src/language/sql/tests/statements.test.ts
- src/language/sql/tokens.ts
- src/language/sql/types.ts
FIxes:
* Support for determining conditionals vs compound statements
* Improved support for `CASE` and `WHEN`
> Improved support for parser conditional and additional statement types

- package.json
- src/connection/serverComponent.ts
- src/dsc.ts
- src/extension.ts
Related to this issue: https://github.com/codefori/vscode-ibmi/issues/2267
If `Config.getServerComponentName` fails to return the currently installed version of the server component (probably happens when installing the extension on a new VSCode instance since it's taken from the extension global storage?), the update manager will try to overwrite the existing file that is not writable (because `chmod 400` is run on it after it's uploaded).
To prevent the updater from failing, this PR adds a new check that will:
- Check if the remote component already exists
- If it exists, the local file's md5 hash is compared to the remote file's
If the md5 hashes are different, the remote file is made writable to ensure the upload will not fail.
This should prevent issues like …
> Check if remote server components actually needs an update

- src/connection/sqlJob.ts
Fixes a bug where the cancel button would display after altering connection settings, when in fact it should remain as play.
> Correctly remove listeners when job is cleaned up

- package-lock.json
- package.json
- src/database/table.ts
- src/language/sql/statement.ts
- src/views/html.ts
- src/views/results/html.ts
- src/views/results/index.ts
- src/views/results/resultSetPanelProvider.ts
Introducing the `update` prefix. When used in combination with a `select` statement that only references one table, then the cells will become updatable. A fully qualified table must be used.
* Try using `update: select * from schema.table`
* Click on a cell for it to become editable
* Either click off the cell or use Enter to submit
* The update is ran as soon as the cell loses focus
Tested column types:
- Numbers
- Strings/Chars
- Date/Times/Timestamp
- Can set as null
> Editable cells

- src/notebooks/logic/chartJs.ts
Reduce chart size to be 80% of the available height or width, whichever is smaller.
At the moment, the charts are generated to the maximum available width, which is a poor experience on desktops. This will limit the size to be the maximum of 80% of the height / width (whichever is smaller).
For example:
> Reduce default chart size to 80% of available screen

- src/language/sql/tests/statements.test.ts
- src/language/sql/tests/tokens.test.ts
- src/language/sql/tokens.ts
Fixes #315 
Modified fixStatement to not assign statementType for "**FOR**" when:
* Previous token is "closebracket"
* Token after the next is the word "**DATA**"
> Prevent sql tokenizer from assuming FOR is a statementType when used with data-type

- src/connection/manager.ts
Fixes #306 
SQLJobManager modified to remove duplicates from library list. This might happen if current library is also in the user library list. The server job shows this in its joblog:
> Remove duplicates from library list

- src/aiProviders/continue/continueContextProvider.ts
- src/views/jobManager/selfCodes/selfCodesResultsView.ts
closes #320 
This pull request includes a small change to the `src/views/jobManager/selfCodes/selfCodesResultsView.ts` file. The change adds a check to ensure that `result.data` is not null before proceeding with the data mapping.
* [`src/views/jobManager/selfCodes/selfCodesResultsView.ts`](diffhunk://#diff-60fcb8be549b022924d679b35b31d2d9cca3998e8ea24632b64e8a8b8d30ad54L148-R148): Added a condition to check if `result.data` is present before processing it.
> fix: check if SELF data is undefined

- package-lock.json
- package.json
- src/database/schemas.ts
- src/views/schemaBrowser/index.ts
The Generate SQL output use the result set from the `QSYS2.GENERATE_SQL` procedure, but this is using a source member (in QTEMP) as intermediate storage and thus have a fixed length source line - 80 characters by default.
This is a problem, since identifiers can be split by a linebreak.
An example is the generated source for view `QSYS2.OBJECT_LOCK_INFO` where the lines containing the SELECT is broken in the middle of identifiers and functions:
This can not be fixed by the SQL formatter, which will replace a linebreak in an identifier by a space:
This PR will change the use of the `QSYS2.GENERATE_SQL` procedure to generate a streamfile instead of a source member and read this file. This will eliminate the problem with linebreaks in identifiers:
After SQL formatting the source will look as …
> Fix linebreaks in generated SQL

- src/views/jobManager/selfCodes/selfCodesResultsView.ts
Implement a null check for selfCodes to prevent potential errors when mapping over the results in the getChildren method.
> Add null check for selfCodes in getChildren method

- .github/workflows/release.yaml
- .github/workflows/webpack_ci.yaml
- src/connection/syntaxChecker/index.ts
It is possible for the component library to be blank due to the nature of how components are cached.
If a component is being checked (first time connection, connect and reload), then the library was being fetched correctly. But, if reconnecting, VS Code assumes the state of the last time it connected (so likely installed) and wasn't getting the install library.
This now gets fetches the library when validating a statement if the library is not set, therefore fixing the broken statement.
> Fix for SQL syntax checker crash due to invalid statement

- src/base.ts
- src/connection/syntaxChecker/index.ts
- src/views/jobManager/editJob/index.ts
- src/views/jobManager/editJob/systemTab.ts
Refactor API imports for consistency and correct broken ASP information retrieval.
> Cleanup API changes and fix ASP info

- src/views/results/resultSetPanelProvider.ts
@phpdave found an issue where if `SYSFILES` didn't exist, then it would print an error to the dev console but would leave the user hanging. This is a simple catch-all for that.
Closes #347
> Add simple try catch to updatable check

- src/views/results/html.ts
Fixed #332
If there is a column where the max length is less than 4, `null` cannot be entered, so the column cannot be set to null.
This changes the logic so if the column is less than 4 characters long, `-` may be used as null.
> Support for null in small columns

- src/connection/syntaxChecker/index.ts
- src/language/providers/completionProvider.ts
- src/language/providers/hoverProvider.ts
- src/language/providers/logic/available.ts
- src/language/providers/parameterProvider.ts
- src/language/providers/problemProvider.ts
Introduce a mechanism to ensure that a job is only grabbed when it is in a safe state. This change enhances the handling of job selection for the language tools. 
Additionally, adjustments to the remote assist functionality ensure it operates correctly based on job readiness.
This was to solve a bug where the syntax checker would hang while a statement was running.
> Only run certain features when job is ready

- package-lock.json
- src/language/sql/statement.ts
- src/language/sql/tests/statements.test.ts
Address lateral use cases without references and enhance performance by caching block objects.
Fixes #359
> Fix lateral use and improve performance with caching

- src/language/providers/hoverProvider.ts
- src/language/providers/logic/callable.ts
- src/language/providers/parameterProvider.ts
- src/language/sql/document.ts
- src/language/sql/statement.ts
- src/language/sql/tests/statements.test.ts
Change the position of brackets in the SQL hover provider to improve code clarity.
Fixes #367
> Adjust bracket positioning in SQL hover provider

- src/database/table.ts
Enhance the SQL query to support both long and short names for table identification in the partition check.
Fixes #364
> Support long and short names in updatable prefix

- package.json
- src/database/table.ts
- src/language/providers/completionProvider.ts
- src/language/providers/contributes.json
- src/language/providers/logic/available.ts
- src/language/providers/statusProvider.ts
Introduce a configuration option to enable the use of system names for columns in SQL syntax assistance, enhancing the content assist functionality.
Closed #346
> Implement option to use system names for columns in content assist

- src/views/results/html.ts
Added column metadata to title property of header-cell in the result view. It will show the column data type, precision and scale.
How to test:
Hover over column headers to view data type
> Show column metadata as header row tooltip in result view

- src/views/results/html.ts
- src/views/schemaBrowser/index.ts
This update ensures that 
* database items in the schema browser are sorted alphabetically, improving usability and navigation (Fixes #376)
* the SQL query has been modified to alias AUTHORIZATION_NAME as USER_NAME in the permissions view.
* made a simple change to the formatting of the type in the hover in the results view
> Fix day one cleanup

- src/connection/manager.ts
Fixes #251 
Modified manager.ts#newJob to use date format = iso (jdbc props). I believe this is the default for ACS RSS.
More info:
https://www.ibm.com/support/pages/how-does-toolbox-jdbc-driver-deal-dates-1940-or-after-2039
> Use date format = iso

- package.json
- src/views/schemaBrowser/contributes.json
Hide schema browser actions that doesn't make sense to show in the command palette
> Hide schema browser actions from command palette

- src/views/results/html.ts
Solves #302.
mapepire-server before 2.1.8 will trim leading whitespaces.
> Don't collapse whitespaces in results and output null in italic

- package.json
- src/Storage.ts
- src/config.ts
- src/views/queryHistoryView/contributes.json
- src/views/queryHistoryView/index.ts
* Adds ability to filter statement history using pre-existing VS Code UI
* New buttons to star/unstar history items, and add a new node under history to see all starred items
* Additional warning button on clearing all history
> Filter and stars

- src/language/providers/index.ts
Remove the peek provider from the language initialization process to streamline functionality.
This is due to a bug in how we're opening the content of the generate statement.
Closes #396
> Disable peek provider in language initialization

- package-lock.json
- src/Storage.ts
- src/language/providers/actionProvider.ts
- src/language/providers/index.ts
- src/language/providers/logic/parse.ts
- src/language/providers/problemProvider.ts
- src/language/sql/document.ts
- src/language/sql/statement.ts
- src/language/sql/tests/statements.test.ts
- src/language/sql/tokens.ts
- src/views/queryHistoryView/index.ts
- src/views/results/binding.ts
- src/views/results/html.ts
- src/views/results/index.ts
- src/views/results/resultSetPanelProvider.ts
Adds a new prefix, `bind`, which allows users to bind values into prior statements that contain parameter markers or host variables.
```
select * from employee where workdept = ? and salary >= :minSalary;
bind: 'A00', 20000;
bind: 'A00', 40000;
```
You'll also find that when executing `bind` statements, history will be updated to store the original statement and will also include storing the `bind` statement being executed into the history of that statement.
Additionally, fixes some bugs for statement execution.
> Support for SQL parameters and binding

- package-lock.json
- package.json
- src/contributes.json
- src/views/schemaBrowser/index.ts
The command is "Generate Insert from File". Tested with the attached files, including with blanks. Will open a new file with the newly generated insert statement. 
Closes issue #169 
[export.csv](https://github.com/user-attachments/files/22007134/export.csv)
[export.json](https://github.com/user-attachments/files/22007135/export.json)
> Create INSERT statement based on imported csv or json
